import Config

config :pop_stash,
  mcp_port: 4001,
  mcp_protocol_version: "2025-03-26",
  ecto_repos: [PopStash.Repo]

# Migration defaults for all tables:
# - UUID primary keys (generated by Postgres)
# - UTC datetime with microseconds for timestamps
config :pop_stash, PopStash.Repo,
  migration_primary_key: [type: :binary_id],
  migration_timestamps: [type: :utc_datetime_usec]

import_config "#{config_env()}.exs"
