import Config

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true

local_docker = System.get_env("LOCAL_DOCKER") == "true"
db_hostname = if local_docker, do: "db", else: "127.0.0.1"
port = if local_docker, do: 5432, else: 5433
typesense_hostname = if local_docker, do: "typesense", else: "127.0.0.1"

# Configure your database
config :pop_stash, PopStash.Repo,
  username: "postgres",
  password: "postgres",
  hostname: db_hostname,
  port: port,
  database: "pop_stash_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  types: PopStash.PostgrexTypes,
  migration_primary_key: [type: :binary_id],
  migration_timestamps: [type: :utc_datetime_usec]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
endpoint_ip = if local_docker, do: {0, 0, 0, 0}, else: {127, 0, 0, 1}

config :pop_stash, PopStashWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: endpoint_ip, port: String.to_integer(System.get_env("PORT") || "4001")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "nqX/mM5wi7kSZfk/Ol/DavUmbaBRYtH4TiBGvvKdTEIKpx6d5rClqOzZ9CF/OFuE",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pop_stash, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pop_stash, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :pop_stash, PopStashWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/pop_stash_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pop_stash, dev_routes: true

# Configure allowed IPs for MCP endpoints
# By default, this includes common Docker and private network ranges.
#
# If you need to allow additional IPs (e.g., if your Docker setup uses unusual networking),
# you can add specific IPs or ranges here. For example:
#   {160, 79, 104, 10}  # Specific IP address
#   {:range, {172, 32, 0, 0}}  # Custom range
#
# To disable IP checking entirely (NOT recommended for production):
#   config :pop_stash, :skip_localhost_check, true
#
config :pop_stash, :allowed_ips, [
  # IPv4 localhost
  {127, 0, 0, 1},
  # IPv6 localhost
  {0, 0, 0, 0, 0, 0, 0, 1},
  # 10.x.x.x Docker/private networks
  {:range, {10, 0, 0, 0}},
  # 172.16.x.x - 172.31.x.x Docker bridge networks
  {:range, {172, 16, 0, 0}},
  {:range, {172, 17, 0, 0}},
  {:range, {172, 18, 0, 0}},
  {:range, {172, 19, 0, 0}},
  {:range, {172, 20, 0, 0}},
  {:range, {172, 21, 0, 0}},
  {:range, {172, 22, 0, 0}},
  {:range, {172, 23, 0, 0}},
  {:range, {172, 24, 0, 0}},
  {:range, {172, 25, 0, 0}},
  {:range, {172, 26, 0, 0}},
  {:range, {172, 27, 0, 0}},
  {:range, {172, 28, 0, 0}},
  {:range, {172, 29, 0, 0}},
  {:range, {172, 30, 0, 0}},
  {:range, {172, 31, 0, 0}},
  # 192.168.x.x local networks
  {:range, {192, 168, 0, 0}},
  # Anthropic CIDR block 160.79.104.0/21 (for Claude Code)
  {:range, {160, 79, 104, 0}},
  {:range, {160, 79, 105, 0}},
  {:range, {160, 79, 106, 0}},
  {:range, {160, 79, 107, 0}},
  {:range, {160, 79, 108, 0}},
  {:range, {160, 79, 109, 0}},
  {:range, {160, 79, 110, 0}},
  {:range, {160, 79, 111, 0}}
]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Override Typesense hostname for Docker vs local development
config :pop_stash, :typesense,
  api_key: "pop_stash_dev_key",
  nodes: [
    %{
      host: typesense_hostname,
      port: 8108,
      protocol: "http"
    }
  ],
  enabled: true
